-- Usuarios
insert into usuario (codigo, clave, tipo_documento, numero_documento, nombres, apellidos, correo, telefono) values ('admin', 'admin', 'CC', '123123', 'Admin', 'Admin', 'henhav@gmail.com', '123456789');


-- Plantillas notificacion
insert into plantilla_notificacion (tipo, descripcion, plantilla) values ('generico', 'Mensaje de prueba genérico', '<html><body><h3 style="background-color: #d2d2ef; padding: 20px;">Hola <strong>${usuario.nombreCompleto}</strong>, bienvenido a la Oficina Virtual del Catastro!</h3><p>${mensaje}</p></body></html>');
insert into plantilla_notificacion (tipo, descripcion, plantilla) values ('usuario_registrado', 'Mensaje de prueba - Usuario registrado', '<html><body><h3 style="background-color: #d2d2ef; padding: 20px;">Hola <strong>${usuario.nombreCompleto}</strong>, bienvenido a la Oficina Virtual del Catastro!</h3><p>La cuenta ha sido creada satisfactoriamente y está asociada a tu dirección de correo <a href="mailto:${usuario.correo}">${usuario.correo}</a>.</p><p>${mensaje}</p></body></html>');
insert into plantilla_notificacion (tipo, descripcion, plantilla) values ('orden_generada', 'Mensaje de prueba - Orden generada', '<html><body><h3 style="background-color: #d2d2ef; padding: 20px;">Hola <strong>${usuario.nombreCompleto}</strong>, orden recibida en Oficina Virtual del Catastro!</h3><p>Se ha creado la orden para la generación de los certificados asociada a tu dirección de correo <ahref="mailto:${usuario.correo}">${usuario.correo}</a>.</p><table cellspacing="0" cellpadding="4" rules="rows" style="color: #1f2240; background-color: #ffffff"><tbody><tr><td colspan="2" style="color: #ffffff; background-color: #1f2240; font-weight: bold">Datos Generales</td></tr><tr><td style="font-weight: bold;">No. Orden</td><td>${mensaje.orden.id}</td></tr><tr><td style="font-weight: bold;">Valor Total</td><td>${mensaje.orden.valorTotal}</td></tr><tr><td style="font-weight: bold;">Estado</td><td>${mensaje.orden.estado}</td></tr><tr><td style="font-weight: bold;">Fecha</td><td>${mensaje.orden.fechaCreacion}</td></tr><tr><td colspan="2" style="color: #ffffff; background-color: #1f2240; font-weight: bold">Cliente</td></tr><tr><td style="font-weight: bold;">Documento</td><td>${mensaje.orden.usuario.tipoDocumento}. ${mensaje.orden.usuario.numeroDocumento}</td></tr><tr><td style="font-weight: bold;">Nombre</td><td>${mensaje.orden.usuario.nombres} ${mensaje.orden.usuario.apellidos}</td></tr></tbody></table><br /><h3>Detalles Items</h3><table><thead style="color: #ffffff; background-color: #1f2240; font-weight: bold"><tr><td colspan="4">Items</td></tr><tr><td>Item</td><td>Cantidad</td><td>Valor Unidad</td><td>Valor Total</td></tr></thead><tbody>#foreach($item in ${mensaje.orden.items})<tr><td style="font-weight: bold;">Certificado ${item.tipoCertificado} ${item.numeroFicha} de ${item.municipio}</td><td>${item.cantidad}</td><td style="text-align: right">${item.valorUnidad}</td><td style="text-align: right">${item.valorTotal}</td></tr>#end<tr><td colspan="3" style="text-align: right; font-weight: bold;">Total Orden:&nbsp;</td><td style="text-align: right">${mensaje.orden.valorTotal}</td></tr></tbody></table><br /> Para realizar el pago, haga click en<br /><a href="${mensaje.pagoUri}">Realizar Pago</a></body></html>');


--Predio
insert into predio (numero_predio, municipio, numero_ficha, matricula, direccion, tipo_documento_usuario, id_propietario) values ('236','DonMatías' ,'3476','000956','cll 33 30 a 10 202','cc','123123');
insert into predio (numero_predio, municipio, numero_ficha, matricula, direccion, tipo_documento_usuario, id_propietario) values ('421','Venecia', '2817','000236','cr 25 27 18','cc','123123');
